baseurl = "http://guides.rxswift.org"
languageCode = "en-us"
title = "RxSwift"
theme = "rx-swift"

[params]
    mainMenu = ["intro", "more-info", "examples"]
    description = "Powerful - Asynchronous - Event Driven"
    analytics = "UA-48560610-8"
    noCategoryLink = true

[permalinks]
	"" = /
	intro = /:section/:filename/

