baseurl = "http://guides.rxswift.org"
languageCode = "en-us"
title = "RxSwift"

[params]
    mainMenu = ["intro", "examples"]
    description = "Powerful - Asynchronous - Event Driven"
    analytics = "UA-48560610-8"
    noCategoryLink = true

