baseurl = "http://es.rxswift.org"
languageCode = "en-us"
title = "RxSwift (Guía en Español)"
theme = "rx-swift"

[params]
    mainMenu = [["intro", "introducción"], ["examples", "ejemplos"]]
    description = "Potente - Asincrono - Dirigido por eventos"
    analytics = "UA-48560610-8"
    noCategoryLink = true

